name: Build and Deploy

on:
  push:
    branches:
      - main
  release:
    types: [published]
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          key: ${{ secrets.HOST_KEY }}
          envs: GITHUB_TOKEN
          script: |
            cd /opt/projectly-landing
            git pull origin main
            docker compose up --pull=always --quiet-pull --build --force-recreate -d
            docker image prune -f